refactor: enhance model selection and input reduction for token limit exceedance
LOGIC-10/RepoAgent pull request #52
Opened 2024-02-20 03:32 UTC by Umpire2018

This commit introduces an improved logic for handling scenarios where the input token count exceeds the maximum limit allowed by the selected model. Now, the code dynamically selects a model with a higher input token capacity if the total token count of system and user prompts surpasses the current model's limit. Additionally, it implements a fallback mechanism to iteratively reduce the input size through specific content removal strategies if no larger model is available. This ensures more flexible and efficient processing of large inputs, enhancing the system's adaptability to varying input sizes.

2024-02-20 03:33 UTC, Umpire2018 commented on repo_agent/chat_engine.py
> +                for attempt in range(2):
将原有的处理发送请求后发生的 `context_length_exceeded` 移动到发送请求前，以保持在发送请求前对 `context window` 进行检查的逻辑。

2024-02-20 03:35 UTC, Umpire2018 commented on repo_agent/chat_engine.py
> +                if total_tokens >= code_max_length:
若请求文本过多，直接引发` ContextLengthExceededError` ，进而无需进行此次交互以减少费用。

2024-02-20 03:40 UTC, Umpire2018 commented on repo_agent/config.py
> +# 获取 yaml 文件中实际使用的模型列表
增加的逻辑用于实现
1. 若用户仅在配置文件中设置了某些模型，如 `gpt-4`, `gpt-3.5-turbo`, 则仅对这几个模型做 `context window` 判断，若超过了长度限制，则仅使用这些模型发起请求。
2. `README` 中可以增加需设置 `fallback model` 的提示。
3.

2024-02-20 13:52 UTC, LOGIC-10 commented on repo_agent/chat_engine.py
> +                    )
这里没有manually的逻辑，如果两次缩减后还是超长就直接跳过了

2024-02-20 13:57 UTC, LOGIC-10 requested changes

2024-02-20 13:57 UTC, LOGIC-10 commented on repo_agent/config.py
> +}
这里模型的长度就填官方的原始长度，原因：
1. 代码使用者看到不会一头雾水，跟官方对应也好说明问题
2. 如果未来max_tokens不是1024了，作为一个变量，读取字典里面的原始长度以后做一个减法就可以，不用这样自己手动每一个都做减法再修改

2024-02-20 14:04 UTC, LOGIC-10 requested changes

2024-02-20 14:04 UTC, LOGIC-10 commented on repo_agent/chat_engine.py
> +                model = max(larger_models, key=larger_models.get)
不需要加一个验证model是否可用吗？如果配置文件里有model但是用户没有配置api_key，或者apikey没有权限？是不是做一个异常处理接一下可能的错误然后继续换model直到可用？（或者在config的字典里判断api_key字段不为空的才能加入最后的字典）。如果换model后还是出错的错误处理，比如继续换其他更长上下文的model直到可用。最后的最后，如果所有model都不可用，就跳二级缩减的逻辑去

2024-02-21 01:11 UTC, Umpire2018 commented on repo_agent/chat_engine.py
> +                        f"after {max_attempts} attempts. Please reduce the input size manually."
1. 这里确实不应有 manually 的逻辑。
2. 此处的用意是当缩减措施无效时抛出一个错误，而不是单纯的 `pass` ，抛出错误的用意是中断当前的某文档生成任务，同时不进行后续的交互逻辑。你觉得呢？

2024-02-21 01:42 UTC, Umpire2018 commented on repo_agent/chat_engine.py
> +                model = max(larger_models, key=larger_models.get)
> 配置文件里有model但是用户没有配置api_key （或者在config的字典里判断api_key字段不为空的才能加入最后的字典）

此不应为与 openai 交互类的目的，加入这个内容个人觉得会引入臃肿。我觉得也许应该有某个库在读取了配置文件后做验证，保证配置项是完整的。

> 如果换model后还是出错的错误处理，比如继续换其他更长上下文的model直到可用。最后的最后，如果所有model都不可用，就跳二级缩减的逻辑去。

当前的做法是在与模型交互前先根据模型 `context window` 来对 `request` 做判断，目的是确保模型 `completion` 效果符合预期。因此在这个情况下，理论上不会出现 `context window exceed`。
退一步讲，若发生了 error , 那么内容应为其他错误，这个时候切换了 `fallback model` ，那么需要重新进行整个 （1）判断 `context window` (2) 重新发送请求的过程。

2024-02-21 06:05 UTC, merged

2024-02-21 06:21 UTC, LOGIC-10 commented on repo_agent/chat_engine.py
> +                        f"after {max_attempts} attempts. Please reduce the input size manually."
不必，这种情况基本不会发生，直接跳过即可，而且抛出报错人类也无法单独解决一个对象代码超长的问题